#!/bin/bash
#comment

echo "inside script"

read -e commitMessage 
echo your commit message :- "$commitMessage" 
var2=$PWD
echo $var2

echo $(git -C $PWD add .)
#echo $(git -C ~/node-programs add .)
echo $(git -C $PWD commit -m "$commitMessage")
