#!/bin/bash
#comment

echo "inside script. Enter you commit message"

read -e commitMessage 
echo $commitMessage

echo "enter you branch"
read -e branch
echo $branch

echo your commit message :- "$commitMessage" 
var2=$PWD
echo $var2

echo $(git -C $PWD add .)
#echo $(git -C ~/node-programs add .)
echo $(git -C $PWD commit -m "$commitMessage")
echo $(git -C $PWD push https://sandyman96:sandeep%4096@github.com/sandyman96/node-programs) -u orgin $branch
